/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package for_log_in;

import for_pets.dogs;

/**
 *
 * @author DERECHO
 */
public class adminpets extends javax.swing.JFrame {

    /**
     * Creates new form adminpets
     */
    public adminpets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        dogicon1 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        cattxt1 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        caticon1 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        dogtxt2 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        birdtxt1 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        birdtxt3 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        birdtxt4 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        birdtxt5 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        dogicon2 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        cattxt2 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        caticon2 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        dogtxt3 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        birdtxt6 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        birdtxt7 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        birdtxt8 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        birdtxt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(570, 30, 0, 150);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-24 (2).png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(640, 0, 20, 10);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel17.setLayout(null);

        dogicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-dog-100 (1).png"))); // NOI18N
        jPanel17.add(dogicon1);
        dogicon1.setBounds(10, 0, 100, 100);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.BorderLayout());

        cattxt1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cattxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cattxt1.setText("Dogs");
        jPanel18.add(cattxt1, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel18);
        jPanel18.setBounds(30, 110, 60, 20);

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 120, 140));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 160));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel20.setLayout(null);

        caticon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cat-100.png"))); // NOI18N
        jPanel20.add(caticon1);
        caticon1.setBounds(10, 0, 100, 100);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new java.awt.BorderLayout());

        dogtxt2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dogtxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dogtxt2.setText("Cats");
        jPanel21.add(dogtxt2, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel21);
        jPanel21.setBounds(30, 110, 60, 20);

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 140));

        jPanel15.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 160));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel13.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel13.add(jLabel2);
        jLabel2.setBounds(10, 0, 100, 100);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        birdtxt1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt1.setText("Birds");
        jPanel14.add(birdtxt1, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel14);
        jPanel14.setBounds(40, 110, 50, 20);

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 140, 160));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel26.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel26.add(jLabel4);
        jLabel4.setBounds(10, 0, 100, 100);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new java.awt.BorderLayout());

        birdtxt3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt3.setText("Birds");
        jPanel27.add(birdtxt3, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel27);
        jPanel27.setBounds(40, 110, 50, 20);

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 140, 160));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel29.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel29.add(jLabel5);
        jLabel5.setBounds(10, 0, 100, 100);

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new java.awt.BorderLayout());

        birdtxt4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt4.setText("Birds");
        jPanel30.add(birdtxt4, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel30);
        jPanel30.setBounds(40, 110, 50, 20);

        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 140, 160));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel32.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel32.add(jLabel6);
        jLabel6.setBounds(10, 0, 100, 100);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setLayout(new java.awt.BorderLayout());

        birdtxt5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt5.setText("Birds");
        jPanel33.add(birdtxt5, java.awt.BorderLayout.CENTER);

        jPanel32.add(jPanel33);
        jPanel33.setBounds(40, 110, 50, 20);

        jPanel31.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 140, 160));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel24.setLayout(null);

        dogicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-dog-100 (1).png"))); // NOI18N
        jPanel24.add(dogicon2);
        dogicon2.setBounds(10, 0, 100, 100);

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setLayout(new java.awt.BorderLayout());

        cattxt2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cattxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cattxt2.setText("Dogs");
        jPanel34.add(cattxt2, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel34);
        jPanel34.setBounds(30, 110, 60, 20);

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 120, 140));

        jPanel15.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 160));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel36.setLayout(null);

        caticon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cat-100.png"))); // NOI18N
        jPanel36.add(caticon2);
        caticon2.setBounds(10, 0, 100, 100);

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setLayout(new java.awt.BorderLayout());

        dogtxt3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dogtxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dogtxt3.setText("Cats");
        jPanel37.add(dogtxt3, java.awt.BorderLayout.CENTER);

        jPanel36.add(jPanel37);
        jPanel37.setBounds(30, 110, 60, 20);

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 140));

        jPanel15.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 160));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel39.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel39.add(jLabel7);
        jLabel7.setBounds(10, 0, 100, 100);

        jPanel40.setBackground(new java.awt.Color(255, 255, 255));
        jPanel40.setLayout(new java.awt.BorderLayout());

        birdtxt6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt6.setText("Birds");
        jPanel40.add(birdtxt6, java.awt.BorderLayout.CENTER);

        jPanel39.add(jPanel40);
        jPanel40.setBounds(40, 110, 50, 20);

        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 140, 160));

        jPanel41.setBackground(new java.awt.Color(255, 255, 255));
        jPanel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel42.setBackground(new java.awt.Color(255, 255, 255));
        jPanel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel42.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel42.add(jLabel8);
        jLabel8.setBounds(10, 0, 100, 100);

        jPanel43.setBackground(new java.awt.Color(255, 255, 255));
        jPanel43.setLayout(new java.awt.BorderLayout());

        birdtxt7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt7.setText("Birds");
        jPanel43.add(birdtxt7, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel43);
        jPanel43.setBounds(40, 110, 50, 20);

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 140, 160));

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel45.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel45.add(jLabel9);
        jLabel9.setBounds(10, 0, 100, 100);

        jPanel46.setBackground(new java.awt.Color(255, 255, 255));
        jPanel46.setLayout(new java.awt.BorderLayout());

        birdtxt8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt8.setText("Birds");
        jPanel46.add(birdtxt8, java.awt.BorderLayout.CENTER);

        jPanel45.add(jPanel46);
        jPanel46.setBounds(40, 110, 50, 20);

        jPanel44.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 140, 160));

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(255, 255, 255));
        jPanel48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel48.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-hummingbird-100.png"))); // NOI18N
        jPanel48.add(jLabel3);
        jLabel3.setBounds(10, 0, 100, 100);

        jPanel49.setBackground(new java.awt.Color(255, 255, 255));
        jPanel49.setLayout(new java.awt.BorderLayout());

        birdtxt2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        birdtxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birdtxt2.setText("Birds");
        jPanel49.add(birdtxt2, java.awt.BorderLayout.CENTER);

        jPanel48.add(jPanel49);
        jPanel49.setBounds(40, 110, 50, 20);

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 140));

        jPanel15.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 140, 160));

        jScrollPane1.setViewportView(jPanel15);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 660, 390);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pets");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 0, 70, 22);

        Back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(0, 0, 40, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        homedashboard up = new homedashboard();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
       dogs up = new dogs();
       up.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jPanel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel birdtxt1;
    private javax.swing.JLabel birdtxt2;
    private javax.swing.JLabel birdtxt3;
    private javax.swing.JLabel birdtxt4;
    private javax.swing.JLabel birdtxt5;
    private javax.swing.JLabel birdtxt6;
    private javax.swing.JLabel birdtxt7;
    private javax.swing.JLabel birdtxt8;
    private javax.swing.JLabel caticon1;
    private javax.swing.JLabel caticon2;
    private javax.swing.JLabel cattxt1;
    private javax.swing.JLabel cattxt2;
    private javax.swing.JLabel dogicon1;
    private javax.swing.JLabel dogicon2;
    private javax.swing.JLabel dogtxt2;
    private javax.swing.JLabel dogtxt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
