/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import config.passwordHasher;
import for_log_in.logIn;
import internalpages.internalusers;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DERECHO
 */
public class changepass extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public changepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        maindesktopuser = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        first_name = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        user_name = new javax.swing.JLabel();
        enpass = new javax.swing.JTextField();
        tppass = new javax.swing.JTextField();
        conpass = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        acc_ln = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        acc_ln1 = new javax.swing.JLabel();
        acc_fn = new javax.swing.JLabel();
        bakcground2 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Change Password");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 140, 20);

        iddisplay.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(255, 255, 255));
        iddisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddisplay.setText("UID");
        jPanel3.add(iddisplay);
        iddisplay.setBounds(140, 0, 90, 20);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 20));

        first_name.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        first_name.setText("Type Old Pass:");
        jPanel2.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        last_name.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        last_name.setText("Enter New Password:");
        jPanel2.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        user_name.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        user_name.setText("Confirm Password:");
        jPanel2.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        enpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enpassActionPerformed(evt);
            }
        });
        jPanel2.add(enpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 140, 30));

        tppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tppassActionPerformed(evt);
            }
        });
        jPanel2.add(tppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, 30));

        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel2.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 30));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        acc_ln.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        acc_ln.setForeground(new java.awt.Color(255, 255, 255));
        acc_ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln.setText("User");
        acc_ln.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_lnMouseClicked(evt);
            }
        });
        jPanel4.add(acc_ln);
        acc_ln.setBounds(20, 0, 50, 30);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 90, 30));

        jLabel8.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LogOut");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(619, 372, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-team-94.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 90));

        acc_ln1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        acc_ln1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln1.setText("User");
        acc_ln1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_ln1MouseClicked(evt);
            }
        });
        jPanel2.add(acc_ln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, -1));

        acc_fn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        acc_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fn.setText("acc_fn");
        acc_fn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_fnMouseClicked(evt);
            }
        });
        jPanel2.add(acc_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        bakcground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paw-3d-symbol-pet-paw.jpg"))); // NOI18N
        bakcground2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bakcground2MouseClicked(evt);
            }
        });
        jPanel2.add(bakcground2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paw-3d-symbol-pet-paw.jpg"))); // NOI18N
        jPanel2.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        maindesktopuser.add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 420);

        jPanel1.add(maindesktopuser);
        maindesktopuser.setBounds(0, 0, 690, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        logIn up = new logIn();
        up .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited

    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         
    }//GEN-LAST:event_jLabel1MouseClicked

    private void acc_lnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_lnMouseClicked
        
      
    }//GEN-LAST:event_acc_lnMouseClicked

    private void tppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tppassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tppassActionPerformed

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void acc_fnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_fnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_fnMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getinstance();
       acc_ln.setText(""+sess.getLname());
       acc_fn.setText(""+sess.getFname());
       iddisplay.setText("USER ID: "+sess.getUid());
      
    }//GEN-LAST:event_formWindowActivated

    private void enpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enpassActionPerformed

    private void acc_ln1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_ln1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_ln1MouseClicked

    private void bakcground2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bakcground2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bakcground2MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        try
        {
            dbConnector dbc = new dbConnector();
            Session sess = Session.getinstance();
            
            String query = "SELECT * FROM tbl_user WHERE u_id = '"+sess.getUid()+"'";
                   ResultSet rs = dbc.getData(query);
                   if(rs.next())
                   {
                       String olddbpass = rs.getString("u_password");
                       String oldhash = passwordHasher.hashPassword(tppass.getText());
                       
                       if(olddbpass.equals(oldhash)){
                           String npass = passwordHasher.hashPassword(enpass.getText());
                           dbc.updateData("UPDATE tbl_user SET u_password = '"+npass+"' WHERE u_id = '"+sess.getUid()+"'");
                           JOptionPane.showMessageDialog(null,"Successfully Updated");
                           logIn ig = new logIn();
                           ig.setVisible(true);
                           this.dispose();
                       }else{
                           JOptionPane.showMessageDialog(null,"Old Password is Incorrect");
                       }
                   }
            
        }catch(SQLException | NoSuchAlgorithmException ex){
            System.out.println(""+ex);
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel acc_fn;
    public javax.swing.JLabel acc_ln;
    public javax.swing.JLabel acc_ln1;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel bakcground2;
    public javax.swing.JTextField conpass;
    public javax.swing.JTextField enpass;
    private javax.swing.JLabel first_name;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel last_name;
    private javax.swing.JDesktopPane maindesktopuser;
    public javax.swing.JTextField tppass;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
