/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbConnector;
import for_log_in.admincustomers;
import internalpages.internalusers;
import javax.swing.JOptionPane;

/**
 *
 * @author DERECHO
 */
public class tofillout extends javax.swing.JFrame {

    /**
     * Creates new form tofillout
     */
    public tofillout() {
        initComponents();
    }
    
     public String action;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerpanel = new javax.swing.JPanel();
        ema = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        c_slabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        home1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        customerpanel.setBackground(new java.awt.Color(255, 255, 255));
        customerpanel.setLayout(null);
        customerpanel.add(ema);
        ema.setBounds(40, 330, 150, 30);
        customerpanel.add(nm);
        nm.setBounds(40, 50, 150, 30);
        customerpanel.add(age);
        age.setBounds(40, 120, 150, 30);
        customerpanel.add(contact);
        contact.setBounds(40, 190, 150, 30);
        customerpanel.add(add);
        add.setBounds(40, 260, 150, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Email");
        customerpanel.add(jLabel2);
        jLabel2.setBounds(40, 310, 50, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name");
        customerpanel.add(jLabel3);
        jLabel3.setBounds(40, 30, 50, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Age");
        customerpanel.add(jLabel4);
        jLabel4.setBounds(40, 100, 50, 20);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Contact");
        customerpanel.add(jLabel5);
        jLabel5.setBounds(40, 170, 50, 20);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Address");
        customerpanel.add(jLabel6);
        jLabel6.setBounds(40, 240, 50, 20);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Gender");
        customerpanel.add(jLabel7);
        jLabel7.setBounds(240, 30, 50, 20);

        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        customerpanel.add(gen);
        gen.setBounds(310, 30, 80, 20);

        jPanel2.setBackground(new java.awt.Color(239, 186, 114));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c_slabel.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        c_slabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c_slabel.setText("Save");
        c_slabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_slabelMouseClicked(evt);
            }
        });
        jPanel2.add(c_slabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 20));

        customerpanel.add(jPanel2);
        jPanel2.setBounds(310, 120, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25-wall.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        customerpanel.add(jLabel1);
        jLabel1.setBounds(170, 30, 550, 340);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-24 (2).png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        customerpanel.add(Exit);
        Exit.setBounds(650, -6, 30, 30);

        home1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        home1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home1.setText("Home");
        home1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home1MouseClicked(evt);
            }
        });
        customerpanel.add(home1);
        home1.setBounds(540, 0, 60, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        customerpanel.add(jComboBox2);
        jComboBox2.setBounds(310, 40, 80, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/25-wall.jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        customerpanel.add(jLabel8);
        jLabel8.setBounds(170, 30, 550, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void home1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home1MouseClicked
        userDashboard up = new userDashboard();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_home1MouseClicked

    private void c_slabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_slabelMouseClicked
       
    }//GEN-LAST:event_c_slabelMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
         dbConnector dbc = new dbConnector();
        if(action.equals("Add")){
            int result = dbc.insertData("INSERT INTO tbl_customers(c_name, c_age, c_gender, c_contact, c_address, c_email, "
                    + "u_status)VALUES('"+nm.getText()+"','"+age.getText()+"','"+contact.getText()+"','"+add.getText()+"','"+ema.getText()+"','"+gen.getSelectedItem()+"')");
            if(result==1){
                JOptionPane.showMessageDialog(null, "Successfully Save");
                admincustomers up = new admincustomers();
                up.setVisible(true);
              this.dispose();
            }else{
                System.out.println("Saving Data Failed");
            }
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tofillout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tofillout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tofillout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tofillout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tofillout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField add;
    private javax.swing.JTextField age;
    public javax.swing.JLabel c_slabel;
    private javax.swing.JTextField contact;
    private javax.swing.JPanel customerpanel;
    private javax.swing.JTextField ema;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JLabel home1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nm;
    // End of variables declaration//GEN-END:variables
}
