/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home_pages2;
import Home_pages2.*;
import Home_pages2.addpet;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author DERECHO
 */
public class addpet extends javax.swing.JInternalFrame {

    /**
     * Creates new form addpet
     */
    public addpet() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi =(BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel2.setLayout(null);

        jPanel7.setLayout(null);
        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 10, 80, 70);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 10, 34, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 210, 390, 100);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel5.setLayout(null);
        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 10, 80, 70);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel14);
        jPanel14.setBounds(120, 10, 0, 20);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(130, 10, 34, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 10, 390, 100);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(null);

        jPanel8.setLayout(null);
        jPanel4.add(jPanel8);
        jPanel8.setBounds(10, 10, 80, 70);

        jPanel12.setLayout(null);
        jPanel4.add(jPanel12);
        jPanel12.setBounds(100, 0, 10, 90);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 210, 0, 0);

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel15.setLayout(null);

        jPanel16.setLayout(null);
        jPanel15.add(jPanel16);
        jPanel16.setBounds(10, 10, 80, 70);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel1");
        jPanel15.add(jLabel2);
        jLabel2.setBounds(130, 10, 34, 14);

        jPanel1.add(jPanel15);
        jPanel15.setBounds(20, 110, 390, 100);

        jPanel18.setBackground(new java.awt.Color(0, 102, 102));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel18.setLayout(null);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel1");
        jPanel18.add(jLabel5);
        jLabel5.setBounds(70, 120, 34, 14);

        jPanel20.setBackground(new java.awt.Color(0, 51, 51));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel20.setLayout(null);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("jLabel1");
        jPanel20.add(jLabel6);
        jLabel6.setBounds(70, 120, 34, 14);

        jPanel18.add(jPanel20);
        jPanel20.setBounds(430, 10, 170, 100);

        jPanel21.setBackground(new java.awt.Color(0, 51, 51));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel21.setLayout(null);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel1");
        jPanel21.add(jLabel7);
        jLabel7.setBounds(70, 120, 34, 14);

        jPanel22.setBackground(new java.awt.Color(0, 51, 51));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel22.setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel1");
        jPanel22.add(jLabel8);
        jLabel8.setBounds(70, 120, 34, 14);

        jPanel21.add(jPanel22);
        jPanel22.setBounds(430, 10, 170, 100);

        jPanel18.add(jPanel21);
        jPanel21.setBounds(440, 10, 170, 100);

        jPanel27.setBackground(new java.awt.Color(0, 51, 51));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel27.setLayout(null);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("jLabel1");
        jPanel27.add(jLabel13);
        jLabel13.setBounds(70, 120, 34, 14);

        jPanel28.setBackground(new java.awt.Color(0, 51, 51));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel28.setLayout(null);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("jLabel1");
        jPanel28.add(jLabel14);
        jLabel14.setBounds(70, 120, 34, 14);

        jPanel27.add(jPanel28);
        jPanel28.setBounds(430, 10, 170, 100);

        jPanel29.setBackground(new java.awt.Color(0, 51, 51));
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel29.setLayout(null);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("jLabel1");
        jPanel29.add(jLabel15);
        jLabel15.setBounds(70, 120, 34, 14);

        jPanel30.setBackground(new java.awt.Color(0, 51, 51));
        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel30.setLayout(null);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("jLabel1");
        jPanel30.add(jLabel16);
        jLabel16.setBounds(70, 120, 34, 14);

        jPanel29.add(jPanel30);
        jPanel30.setBounds(430, 10, 170, 100);

        jPanel27.add(jPanel29);
        jPanel29.setBounds(440, 10, 170, 100);

        jPanel18.add(jPanel27);
        jPanel27.setBounds(440, 110, 170, 100);

        jPanel1.add(jPanel18);
        jPanel18.setBounds(430, 210, 170, 100);

        jPanel23.setBackground(new java.awt.Color(0, 51, 51));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel23.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("jLabel1");
        jPanel23.add(jLabel9);
        jLabel9.setBounds(70, 120, 34, 14);

        jPanel24.setBackground(new java.awt.Color(0, 51, 51));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel24.setLayout(null);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("jLabel1");
        jPanel24.add(jLabel10);
        jLabel10.setBounds(70, 120, 34, 14);

        jPanel23.add(jPanel24);
        jPanel24.setBounds(430, 10, 170, 100);

        jPanel25.setBackground(new java.awt.Color(0, 51, 51));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel25.setLayout(null);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("jLabel1");
        jPanel25.add(jLabel11);
        jLabel11.setBounds(70, 120, 34, 14);

        jPanel26.setBackground(new java.awt.Color(0, 51, 51));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel26.setLayout(null);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("jLabel1");
        jPanel26.add(jLabel12);
        jLabel12.setBounds(70, 120, 34, 14);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(430, 10, 170, 100);

        jPanel23.add(jPanel25);
        jPanel25.setBounds(440, 10, 170, 100);

        jPanel1.add(jPanel23);
        jPanel23.setBounds(430, 10, 170, 100);

        jPanel31.setBackground(new java.awt.Color(0, 51, 51));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel31.setLayout(null);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("jLabel1");
        jPanel31.add(jLabel17);
        jLabel17.setBounds(70, 120, 34, 14);

        jPanel32.setBackground(new java.awt.Color(0, 51, 51));
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel32.setLayout(null);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("jLabel1");
        jPanel32.add(jLabel18);
        jLabel18.setBounds(70, 120, 34, 14);

        jPanel31.add(jPanel32);
        jPanel32.setBounds(430, 10, 170, 100);

        jPanel33.setBackground(new java.awt.Color(0, 51, 51));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel33.setLayout(null);

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("jLabel1");
        jPanel33.add(jLabel19);
        jLabel19.setBounds(70, 120, 34, 14);

        jPanel34.setBackground(new java.awt.Color(0, 51, 51));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel34.setLayout(null);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("jLabel1");
        jPanel34.add(jLabel20);
        jLabel20.setBounds(70, 120, 34, 14);

        jPanel33.add(jPanel34);
        jPanel34.setBounds(430, 10, 170, 100);

        jPanel31.add(jPanel33);
        jPanel33.setBounds(440, 10, 170, 100);

        jPanel35.setBackground(new java.awt.Color(0, 51, 51));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel35.setLayout(null);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("jLabel1");
        jPanel35.add(jLabel21);
        jLabel21.setBounds(70, 120, 34, 14);

        jPanel36.setBackground(new java.awt.Color(0, 51, 51));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel36.setLayout(null);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("jLabel1");
        jPanel36.add(jLabel22);
        jLabel22.setBounds(70, 120, 34, 14);

        jPanel35.add(jPanel36);
        jPanel36.setBounds(430, 10, 170, 100);

        jPanel37.setBackground(new java.awt.Color(0, 51, 51));
        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel37.setLayout(null);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("jLabel1");
        jPanel37.add(jLabel23);
        jLabel23.setBounds(70, 120, 34, 14);

        jPanel38.setBackground(new java.awt.Color(0, 51, 51));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel38.setLayout(null);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("jLabel1");
        jPanel38.add(jLabel24);
        jLabel24.setBounds(70, 120, 34, 14);

        jPanel37.add(jPanel38);
        jPanel38.setBounds(430, 10, 170, 100);

        jPanel35.add(jPanel37);
        jPanel37.setBounds(440, 10, 170, 100);

        jPanel31.add(jPanel35);
        jPanel35.setBounds(440, 110, 170, 100);

        jPanel1.add(jPanel31);
        jPanel31.setBounds(430, 110, 170, 100);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
